### ISSUE TITLE
[CLIENT] retired coder

### ISSUE THREAD

**Issue by Carmer** [thompickett/super-coders#42]
As a user if I visit an item page and that item has been retired
      Then I should still be able to access the item page
      And I should not be able to add the item to their cart
      And I should see in place of the "Add to Cart" button or link - "Item Retired"

**Comment by s-espinosa** [comment]
X As a user if I visit an item page and that item has been retired
X      Then I should still be able to access the item page
X      And I should not be able to add the item to their cart
X      And I should see in place of the "Add to Cart" button or link - "Item Retired"
