### ISSUE TITLE
[CLIENT] Authenticated users security

### ISSUE THREAD

**Issue by Carmer** [thompickett/super-coders#44]
Background: An authenticated user and the ability to add an admin user
      As an Authenticated User
      I cannot view another user's private data (current or past orders, etc)
      I cannot view the administrator screens or use admin functionality
      I cannot make myself an admin

**Comment by thePaulista** [comment]
Background: An authenticated user and the ability to add an admin user
    X  As an Authenticated User
    XI cannot view another user's private data (current or past orders, etc)
     XI cannot view the administrator screens or use admin functionality
     XI cannot make myself an admin
