### ISSUE TITLE
[CLIENT] unauthenticated user security

### ISSUE THREAD

**Issue by Carmer** [thompickett/super-coders#45]
Background: An unauthenticated user and their abilities
      As an Unuthenticated User
      I cannot view another user's private data, such as current order, etc.
      I should be redirected to login/create account when I try to check out.
      I cannot view the administrator screens or use administrator functionality.
      I cannot make myself an administrator.

**Comment by thePaulista** [comment]
Background: An unauthenticated user and their abilities
X      As an Unuthenticated User
 X    I cannot view another user's private data, such as current order, etc.
  X    I should be redirected to login/create account when I try to check out.
X      I cannot view the administrator screens or use administrator functionality.
X      I cannot make myself an administrator.
