### ISSUE TITLE
[CLIENT] Admin User Dashboard

### ISSUE THREAD

**Issue by Carmer** [thompickett/super-coders#62]
As an Admin
      When I visit "/admin/dashboard"
      I will see a heading on the page that says "Admin Dashboard"
      As a registered user
      When I visit "/admin/dashboard"
      I get a 404
      As an unregistered user
      When I visit "/admin/dashboard"
      I get a 404

**Comment by thePaulista** [comment]
As an Admin
X      When I visit "/admin/dashboard"
   X   I will see a heading on the page that says "Admin Dashboard"
      X As a registered user
      X When I visit "/admin/dashboard"
      X I get a 404
      X As an unregistered user
      X When I visit "/admin/dashboard"
      X I get a 404
