### ISSUE TITLE
[CLIENT] Admin edits an item

### ISSUE THREAD

**Issue by s-espinosa** [thompickett/super-coders#82]
Background: with an existing item
As an admin
When I visit "admin/items"
And I click "Edit"
Then my current path should be "/admin/items/:ITEM_ID/edit"
And I should be able to upate title, description, image, and status

**Comment by thePaulista** [comment]
X   Background: with an existing item
X   As an admin
X   When I visit "admin/items"
X   And I click "Edit"
X   Then my current path should be "/admin/items/:ITEM_ID/edit"
And I should be able to upate title, description, image, and status
NOTE:::::: coder is getting updated, but category is not.  check params

**Comment by thePaulista** [comment]
def update.....something wrong with the category_id

**Comment by s-espinosa** [comment]
Category ID now working.
